timezone: America/New_York

# own settings
name: ericsims.github.io/portfolio-template
description: Portfolio Template
copyright: 2018

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "basic"
  -
    scope:
      path: "projects"
    values:
      layout: "project"
